"""init

Revision ID: dece98001b44
Revises: 
Create Date: 2025-05-11 01:47:13.579014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dece98001b44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('image', name='nsassettype'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('namespace_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ns'
    )
    op.create_table('shopping_lists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('namespace_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ns'
    )
    op.create_table('shopping_item_master_icons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('emoji', 'image', name='shoppingitemmastericontype'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('namespace_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['ns.assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ns'
    )
    op.create_table('shopping_item_masters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('namespace_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['ns.shopping_item_master_icons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ns'
    )
    op.create_table('shopping_list_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shopping_list_id', sa.String(), nullable=True),
    sa.Column('shopping_item_master_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('shopped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shopping_item_master_id'], ['ns.shopping_item_masters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['ns.shopping_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ns'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_list_items', schema='ns')
    op.drop_table('shopping_item_masters', schema='ns')
    op.drop_table('shopping_item_master_icons', schema='ns')
    op.drop_table('shopping_lists', schema='ns')
    op.drop_table('assets', schema='ns')
    # ### end Alembic commands ###
