{{- if .Values.serviceAccount.create -}}
# フロントエンド / バックエンド / 任意のマイグレーション Job が共有する ServiceAccount です。
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "myhome-tools.serviceAccountName" . }}
  labels:
    {{- include "myhome-tools.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
